### ISSUE TITLE
Firefox reconnects instead of close when navigating away from current page

### ISSUE THREAD

**Issue by oyvindhorneland** [Atmosphere/atmosphere-javascript#143] opened 2015-01-14 08:39 UTC
After update from javascript 2.2.5 to 2.2.6 (and also tried 2.2.7), firefox will reconnect before closing the connection. Works well in Chrome and IE.

Log for Firefox with 2.2.7-javascript (snapshot):
```
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: Firing onReconnect
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: Firing onReconnect
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxrequest.onerror
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: Firing onReopen
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: Firing onReopen
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: Firing onMessage
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: Firing onMessage
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
Wed Jan 14 2015 09:25:38 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
Closing
Wed Jan 14 2015 09:25:39 GMT+0100 Atmosphere: Firing onClose
```

Log for Chrome:
```
Closing
Wed Jan 14 2015 09:29:53 GMT+0100 (W. Europe Standard Time) Atmosphere: Firing onClose
```

Firefox: 35
atmosphere-javascript: 2.2.6 and current snapshot for 2.2.7
atmosphere-runtime: 2.2.4
transport: long-polling
jetty: 9.2.4.v20141103

**Comment by oyvindhorneland** [comment] 2015-01-14 10:05
It seems to be working fine in Firefox if I add the atmosphere.unsubscribe to the beforeunload event.

Change section from:
```
    atmosphere.util.on(window, "unload", function (event) {
        atmosphere.unsubscribe();
    });
```

.. to:
```
    atmosphere.util.on(window, "unload", function (event) {
        atmosphere.util.debug(new Date() + " Atmosphere: " + "DEBUG: unload event");
        atmosphere.unsubscribe();
    });

    atmosphere.util.on(window, "beforeunload", function (event) {
        atmosphere.util.debug(new Date() + " Atmosphere: " + "DEBUG: beforeunload event");
        atmosphere.unsubscribe();
    });
```

log:
```
Wed Jan 14 2015 10:56:58 GMT+0100 Atmosphere: DEBUG: beforeunload event
Closing
Wed Jan 14 2015 10:56:58 GMT+0100 Atmosphere: Firing onClose
Wed Jan 14 2015 10:56:58 GMT+0100 Atmosphere: Closed but not firing onClose
Wed Jan 14 2015 10:56:58 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
Wed Jan 14 2015 10:57:00 GMT+0100 Atmosphere: DEBUG: unload event
```

Possible solution? Works in FF, IE and Chrome.

**Comment by jfarcand** [comment] 2015-01-14 13:16
@oyvindhorneland Pull request welcomed so I can play with it. Thanks!

**Comment by oyvindhorneland** [comment] 2015-01-14 14:01
Added pull request https://github.com/Atmosphere/atmosphere-javascript/pull/144

**Comment by seamusmac** [comment] 2015-03-18 15:07
@jfarcand 
I have been trying to reproduce this, but haven't been able to so far.

@oyvindhorneland
Do you have the steps to reproduce this, or can you check to see if it is still a bug or not, with latest 2.2.9-SNAPSHOT?

**Comment by jfarcand** [comment] 2015-03-18 16:48
@seamusmac I didn't had a chance to look at it yet. So the pressure is on @oyvindhorneland :-)

**Comment by oyvindhorneland** [comment] 2015-03-18 18:37
I'll probably be able to upgrade and retest tomorrow. It was previously reproduced by connecting with Firefox in long polling mode and then browse to a different page without an explicit disconnect. Firefox would always reconnect multiple times as described before navigating to the next page.

**Comment by oyvindhorneland** [comment] 2015-03-19 12:10
Atmosphere-runtime: 2.2.6
Atmosphere-javascript: 2.2.9 snapshot

**Test:**
1. Connect
2. Navigate away from current page

**Chrome:**
> Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: unload event
Closing
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: Firing onClose
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: Closed but not firing onClose
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
XHR finished loading: GET "http://localhost/....tmosphere-tracking-id=d6700c62-74e2-43a2-b59c-917cedb7577b&_=1426766166163".
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 4
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: ajaxRequest.onreadystatechange, new state: 4
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: ajaxrequest.onabort
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: Closed but not firing onClose
Thu Mar 19 2015 12:56:06 GMT+0100 (W. Europe Standard Time) Atmosphere: Closed but not firing onClose
Navigated to http://......

**Firefox:**
> Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 4
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: Firing onReconnect
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: Firing onReconnect
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: ajaxrequest.onerror
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 2
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 3
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: unload event
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: Firing onClose
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: Closed but not firing onClose
Thu Mar 19 2015 12:57:03 GMT+0100 Atmosphere: ajaxRequest.onreadystatechange, new state: 4


I'll set up the sample application and see if I can reproduce there as well.

**Comment by oyvindhorneland** [comment] 2015-03-19 20:17
* Server: Jetty 9.2.10.v20150310 (no modifications)
* Sample: atmosphere-atmospherehandler-pubsub-2.2.6
  * Modifications to sample
    * atmosphere-javascript 2.2.9 (snapshot)
    * index.html: logLevel: 'debug'
* Test
  * Using http://localhost/atmosphere-atmospherehandler-pubsub-2.2.6/
  * Connect with long-polling to a topic (call whatever you want)
  * Navigate to http://localhost

Firebug reports:
![image](https://cloud.githubusercontent.com/assets/1670211/6739944/acf9f384-ce7c-11e4-97c5-8f2dce59347e.png)

**Comment by jfarcand** [comment] 2015-04-01 13:04
@oyvindhorneland I think we should just re-add your patch with a check that only apply to Firefox. What do you think?

**Comment by oyvindhorneland** [comment] 2015-04-01 17:00
@jfarcand Sounds good to me.

**Comment by oyvindhorneland** [comment] 2015-04-14 09:58
Pull request #160 added

**Comment by Artur-** [comment] 2015-04-16 06:56
Did you test this with file downloads? If you download a file, the browser will fire "beforeunload" and then just stay on the same page after it has noticed that the server response actually was only a file to download.

**Comment by jfarcand** [comment] 2015-04-16 12:11
@Artur- With Firefox?

**Comment by oyvindhorneland** [comment] 2015-04-17 06:54
@Artur- @jfarcand Just tested this now with a download link and @Artur- is unfortunately correct and we need to remove this fix again. I'll check if the reconnect behavior is still present with the new 2.2.10.

**Comment by oyvindhorneland** [comment] 2015-04-17 07:03
PR #162 added

**Comment by oyvindhorneland** [comment] 2015-04-17 07:10
The reconnect issue is still present in Firefox with 2.2.11 SNAPSHOT.

![image](https://cloud.githubusercontent.com/assets/1670211/7197439/7c37331c-e4e1-11e4-9ca3-bdc8cef1afcc.png)

**Comment by jfarcand** [comment] 2015-04-17 11:35
Actually it will also do the same behavior with Chrome/Safari and websocket starting with 2.2.10. So I think I won't fix that issue now as it seems other framework are also doing that because it is hard to detect if the browser navigated away, server down or connection dropped in some scenario.

**Closed by jfarcand** 2015-04-17 11:35 UTC
Labels: 2.2.10

**Comment by krskrs** [comment] 2015-06-11 21:12
Hi, I stumbled upon this bug while developing with the framework and testing with Firefox, however it looks like on latest chrome (windows) this bug doesn't occur. (Chrome v43.0.2357.124)

I'd like to look further into this issue, but I don't know if I will be able to find some time soon, so I'm writing just a couple of notes, in case jfarcand would like to comment on them :)

1) Since this wrong reconnection behavior started with the 2.2.6 js update, knowing exactly what changed from 2.2.5 which caused the bug would be important. Has that particular change been identified?
2) I saw a fix with unsubscribe() in the beforeunload event, but maybe looking at what is causing the reconnection only on Firefox and trying to patch at that level might led to a better result, unless the unload case collides with other real disconnection scenarios where reconnection is actually needed. However, the fact it doesn't happen with chrome gives me some hope :)

**Comment by oyvindhorneland** [comment] 2015-07-02 07:47
@jfarcand What do you think about a workaround for Firefox where 
1. beforeunload sets a beforeunload flag that is reverted after a short timeout
2. reconnectF checks if beforeunload flag is set and delays reconnect

Expected result:
1. If unload is not called after beforeunload the atmosphere client will reconnect (reconnectF)
2. If unload is reached, reconnectF will be blocked from reconnecting

**Comment by jfarcand** [comment] 2015-07-02 12:27
@oyvindhorneland +1 I'm pretty busy those days so if you have the cycle do a pull request and I will evaluate it.

**Comment by asotog** [comment] 2016-02-25 03:29
Tested today with latest js and jars and happens on safari as well, java lib version 2.4.0 and js 2.3.2, we had old version (2.1.1 on java and 2.1.5 on js) and this was not happening, issue happens on newer version on both safari and firefox
